"""first

Revision ID: 8067f1a2b202
Revises: 
Create Date: 2024-02-02 10:34:13.169281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8067f1a2b202'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owners')),
    sa.UniqueConstraint('name', name=op.f('uq_owners_name'))
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('age >= 0', name=op.f('ck_dogs_age_not_neg')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_dogs_owner_id_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dogs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dogs')
    op.drop_table('owners')
    # ### end Alembic commands ###
