"""add breed col

Revision ID: 151dfb420757
Revises: c8577a4c6f9c
Create Date: 2024-01-30 10:42:11.861105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151dfb420757'
down_revision = 'c8577a4c6f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
