"""add owners

Revision ID: cfa7919f3ffe
Revises: 151dfb420757
Create Date: 2024-02-01 10:45:24.258630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa7919f3ffe'
down_revision = '151dfb420757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owners'))
    )
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_dogs_owner_id_owners'), 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dogs_owner_id_owners'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    op.drop_table('owners')
    # ### end Alembic commands ###
