"""add owners fk

Revision ID: 5a3302e0f994
Revises: 728911f98603
Create Date: 2024-06-25 11:31:26.762043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3302e0f994'
down_revision = '728911f98603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pets_owner_id_owners'), 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pets_owner_id_owners'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
