"""add owners

Revision ID: 5dfcc50294e6
Revises: 6af05905125b
Create Date: 2024-04-02 11:36:59.972527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfcc50294e6'
down_revision = '6af05905125b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_dogs_owner_id_owners'), 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dogs_owner_id_owners'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
