"""add users

Revision ID: f040e606155f
Revises: bc23125b9def
Create Date: 2024-04-09 10:18:56.130842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f040e606155f'
down_revision = 'bc23125b9def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_dogs_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_dogs_name'), type_='unique')

    op.drop_table('users')
    # ### end Alembic commands ###
