"""add users table

Revision ID: 17554922aa55
Revises: 248e0209c361
Create Date: 2024-01-30 13:05:37.386485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17554922aa55'
down_revision = '248e0209c361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
