"""add Owner

Revision ID: 248e0209c361
Revises: 837aec6eceec
Create Date: 2024-01-25 14:19:52.176543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248e0209c361'
down_revision = '837aec6eceec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owners'))
    )
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_dogs_owner_id_owners'), 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dogs_owner_id_owners'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    op.drop_table('owners')
    # ### end Alembic commands ###
