"""add Dog

Revision ID: 837aec6eceec
Revises: 
Create Date: 2024-01-25 14:03:12.138617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837aec6eceec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.CheckConstraint('age >= 0', name=op.f('ck_dogs_age_not_neg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dogs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dogs')
    # ### end Alembic commands ###
