"""add owners

Revision ID: 728911f98603
Revises: d88283f3364a
Create Date: 2024-06-25 10:39:07.056261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728911f98603'
down_revision = 'd88283f3364a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owners'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
